version: "3.6"
#volumes:
#  database: {}
services:

  #Mysql
  db:
#    restart: always
    image: mysql:8
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      MYSQL_ROOT_PASSWORD: "Abc123#"
      MYSQL_DATABASE: "demo"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - nam-network

  #NGINX
  nginx:
    image: nginx:latest
#    build:
#      context: ./docker/nginx
#      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - phpfpm:phpfpm
      - elasticsearch
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
#      - ./docker/nginx/conf.d/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
      - ./app:/home/www:delegated
      - ./docker/log/nginx:/var/log/nginx:delegated
      - ./docker/nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./docker/nginx/ssl/localhost.key:/etc/ssl/private/localhost.key
    networks:
      - nam-network
#  varnish:
##    restart: always
#    #    image: varnish:6
#    build:
#      context: ./docker/varnish
#    security_opt:
#      - label:user:1001
#    cap_add:
#      - ALL
#    cap_drop:
#      - NET_ADMIN
#      - SYS_ADMIN
#    environment:
#      - VIRTUAL_HOST=magento.local
#      - VIRTUAL_PORT=80
#      - HTTPS_METHOD=noredirect
#    volumes:
#      - ./docker/varnish/default.vcl:/etc/varnish/default.vcl
#      - /sys/fs/cgroup:/host/cgroup:ro
#    ports:
#      - "80:80"
#    mem_limit: 5g
##    eec: 6g
#    depends_on:
#      - nginx
#    networks:
#      - nam-network
  #PHP
  phpfpm:
    build:
      context: ./docker/phpfpm
      dockerfile: php-fpm.docker
    links:
       - db:db
    volumes:
       - ./app:/home/www:delegated
       - ./docker/phpfpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /home/www
    mem_limit: 5g
    expose:
      - "9000"
      - "9009"
#    ports:
#      - "9000:9000"
#      - "9009:9009"
    extra_hosts:
      - host.docker.internal:192.168.16.10
#    memswap_limit: 6g
    networks:
      - nam-network
    # phpmyadmin
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    #volumes:
#    #  - ./php.ini:/usr/local/etc/php/php.ini
#    environment:
#      VIRTUAL_HOST: "phpmyadmin.demo.local"
#      PMA_HOSTS: "db"
#      PMA_USER: "root"
#      PMA_ROOT_PASSWORD: "Abc123#"
#      PMA_PASSWORD: "Abc123#"
#    depends_on:
#      - db
  elasticsearch:
    build:
      context: ./docker/elasticsearch
      args:
        - ELK_VERSION=7.7.0
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
#      - cluster.name=elasticsearch-cluster
#      - node.name=elasticsearch-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
#      - cluster.initial_master_nodes=elasticsearch-node
      - "discovery.type=single-node"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
#    depends_on:
#      - phpfpm
    networks:
      - nam-network

  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - nam-network

volumes:
  elasticsearch:
    driver: local
networks:
  nam-network:
    driver: bridge